"use client";

import { useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import {
  FileBarChart,
  Plus,
  Loader2,
  X,
  Download,
} from "lucide-react";
import {
  useMinistryReports,
  useGenerateMinistryReport,
} from "@/superadmin/lib/hooks/use-ministry";
import { PageHeader } from "@/superadmin/components/shared/misc/page-header";
import { DataTable } from "@/superadmin/components/shared/data-table/data-table";
import { StatusBadge } from "@/superadmin/components/shared/feedback/status-badge";
import { TableSkeleton } from "@/superadmin/components/shared/feedback/loading-skeleton";
import { ErrorState } from "@/superadmin/components/shared/feedback/error-state";
import { FormField, FormSelect } from "@/superadmin/components/shared/forms/form-field";
import { formatDate, formatCompact } from "@/superadmin/lib/utils/format";
import { cn } from "@/superadmin/lib/utils/cn";
import type { ColumnDef } from "@tanstack/react-table";
import type { MinistryReport } from "@/superadmin/lib/api/types/ministry.types";

const REPORT_TYPES = [
  { value: "", label: "All Types" },
  { value: "national", label: "National" },
  { value: "regional", label: "Regional" },
  { value: "institutional", label: "Institutional" },
  { value: "compliance", label: "Compliance" },
  { value: "budget", label: "Budget" },
];

const REPORT_TYPE_OPTIONS = REPORT_TYPES.filter((t) => t.value !== "");

const typeVariant: Record<string, "default" | "info" | "success" | "warning" | "muted"> = {
  national: "default",
  regional: "info",
  institutional: "muted",
  compliance: "warning",
  budget: "success",
};

const statusVariant: Record<string, "default" | "success" | "warning" | "danger"> = {
  generating: "warning",
  completed: "success",
  failed: "danger",
};

const columns: ColumnDef<MinistryReport, unknown>[] = [
  {
    accessorKey: "title",
    header: "Title",
    cell: ({ row }) => (
      <span className="font-medium">{row.original.title}</span>
    ),
  },
  {
    accessorKey: "type",
    header: "Type",
    cell: ({ row }) => (
      <StatusBadge variant={typeVariant[row.original.type] ?? "muted"}>
        {row.original.type}
      </StatusBadge>
    ),
  },
  {
    accessorKey: "status",
    header: "Status",
    cell: ({ row }) => (
      <StatusBadge
        variant={statusVariant[row.original.status] ?? "muted"}
        dot
      >
        {row.original.status}
      </StatusBadge>
    ),
  },
  {
    accessorKey: "generatedBy",
    header: "Generated By",
    cell: ({ row }) => (
      <span className="text-muted-foreground">{row.original.generatedBy}</span>
    ),
  },
  {
    accessorKey: "createdAt",
    header: "Date",
    cell: ({ row }) => (
      <span className="text-muted-foreground">
        {formatDate(row.original.createdAt)}
      </span>
    ),
  },
  {
    accessorKey: "fileSize",
    header: "Size",
    cell: ({ row }) =>
      row.original.fileSize ? (
        <span className="text-muted-foreground">
          {formatCompact(row.original.fileSize)} B
        </span>
      ) : (
        <span className="text-muted-foreground">--</span>
      ),
  },
  {
    id: "download",
    header: "",
    cell: ({ row }) =>
      row.original.downloadUrl && row.original.status === "completed" ? (
        <a
          href={row.original.downloadUrl}
          className="inline-flex items-center gap-1 rounded-md px-2 py-1 text-xs font-medium text-portal-accent transition-colors hover:bg-portal-accent-light"
          onClick={(e) => e.stopPropagation()}
        >
          <Download className="h-3.5 w-3.5" />
          Download
        </a>
      ) : null,
  },
];

export default function MinistryReportsPage() {
  const [typeFilter, setTypeFilter] = useState("");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [title, setTitle] = useState("");
  const [reportType, setReportType] = useState("national");
  const [region, setRegion] = useState("");
  const [dateFrom, setDateFrom] = useState("");
  const [dateTo, setDateTo] = useState("");

  const { data, isLoading, isError, refetch } = useMinistryReports({
    type: typeFilter || undefined,
  });
  const generateReport = useGenerateMinistryReport();

  const handleGenerate = async () => {
    if (!title.trim()) return;
    const parameters: Record<string, string> = {};
    if (region) parameters.region = region;
    if (dateFrom) parameters.dateFrom = dateFrom;
    if (dateTo) parameters.dateTo = dateTo;

    await generateReport.mutateAsync({
      title: title.trim(),
      type: reportType,
      parameters,
    });
    setDialogOpen(false);
    setTitle("");
    setReportType("national");
    setRegion("");
    setDateFrom("");
    setDateTo("");
  };

  if (isLoading) {
    return (
      <div className="space-y-6">
        <PageHeader
          icon={FileBarChart}
          title="Reports"
          description="Generate and manage national education reports"
        />
        <TableSkeleton rows={6} />
      </div>
    );
  }

  if (isError) {
    return (
      <div className="space-y-6">
        <PageHeader
          icon={FileBarChart}
          title="Reports"
          description="Generate and manage national education reports"
        />
        <ErrorState
          title="Failed to load reports"
          message="Could not retrieve report data. Please try again."
          onRetry={() => refetch()}
        />
      </div>
    );
  }

  const reports = data?.reports ?? [];

  return (
    <div className="space-y-6">
      <PageHeader
        icon={FileBarChart}
        title="Reports"
        description="Generate and manage national education reports"
        actions={
          <Dialog.Root open={dialogOpen} onOpenChange={setDialogOpen}>
            <Dialog.Trigger asChild>
              <button className="inline-flex items-center gap-1.5 rounded-lg bg-portal-accent px-4 py-2 text-sm font-medium text-portal-accent-foreground transition-colors hover:bg-portal-accent-hover">
                <Plus className="h-4 w-4" />
                Generate Report
              </button>
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay className="fixed inset-0 z-50 bg-black/40 backdrop-blur-sm data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0" />
              <Dialog.Content className="fixed left-1/2 top-1/2 z-50 w-full max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-xl border border-border bg-card p-6 shadow-lg data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95">
                <div className="flex items-center justify-between">
                  <Dialog.Title className="text-lg font-semibold">
                    Generate Report
                  </Dialog.Title>
                  <Dialog.Close className="rounded-md p-1 text-muted-foreground hover:text-foreground">
                    <X className="h-4 w-4" />
                  </Dialog.Close>
                </div>
                <Dialog.Description className="mt-1 text-sm text-muted-foreground">
                  Configure and generate a new education report.
                </Dialog.Description>

                <div className="mt-4 space-y-4">
                  <FormField
                    label="Report Title"
                    value={title}
                    onChange={(e) => setTitle(e.target.value)}
                    placeholder="e.g., Q1 National Compliance Report"
                    required
                  />

                  <FormSelect
                    label="Report Type"
                    options={REPORT_TYPE_OPTIONS}
                    value={reportType}
                    onChange={(e) => setReportType(e.target.value)}
                    required
                  />

                  <FormField
                    label="Region"
                    value={region}
                    onChange={(e) => setRegion(e.target.value)}
                    placeholder="e.g., North (optional)"
                  />

                  <div className="grid grid-cols-2 gap-4">
                    <FormField
                      label="Date From"
                      type="date"
                      value={dateFrom}
                      onChange={(e) => setDateFrom(e.target.value)}
                    />
                    <FormField
                      label="Date To"
                      type="date"
                      value={dateTo}
                      onChange={(e) => setDateTo(e.target.value)}
                    />
                  </div>
                </div>

                <div className="mt-6 flex justify-end gap-3">
                  <Dialog.Close className="rounded-lg border border-border px-4 py-2 text-sm font-medium transition-colors hover:bg-muted">
                    Cancel
                  </Dialog.Close>
                  <button
                    onClick={handleGenerate}
                    disabled={!title.trim() || generateReport.isPending}
                    className="flex items-center gap-2 rounded-lg bg-portal-accent px-4 py-2 text-sm font-medium text-portal-accent-foreground transition-colors hover:bg-portal-accent-hover disabled:opacity-50"
                  >
                    {generateReport.isPending && (
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                    )}
                    Generate
                  </button>
                </div>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root>
        }
      />

      {/* Type Filter Tabs */}
      <div className="flex gap-1 overflow-x-auto rounded-lg border border-border bg-muted/50 p-1">
        {REPORT_TYPES.map((rt) => (
          <button
            key={rt.value}
            onClick={() => setTypeFilter(rt.value)}
            className={cn(
              "whitespace-nowrap rounded-md px-4 py-2 text-sm font-medium capitalize transition-colors",
              typeFilter === rt.value
                ? "bg-background text-foreground shadow-sm"
                : "text-muted-foreground hover:text-foreground"
            )}
          >
            {rt.label}
          </button>
        ))}
      </div>

      {/* Reports Table */}
      <DataTable
        columns={columns}
        data={reports}
        searchKey="title"
        searchPlaceholder="Search reports..."
        emptyTitle="No reports found"
        emptyDescription="Generate your first report using the button above."
      />
    </div>
  );
}
